/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Antonio
 */
public class MusicaView extends javax.swing.JPanel {

    /**
     * Creates new form CardMusica
     */
    public MusicaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaMusica = new javax.swing.JTextField();
        btnBuscarMusica = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblImagemMusica = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAcordeMusica = new javax.swing.JLabel();

        txtBuscaMusica.setText("Buscar música");
        txtBuscaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaMusicaActionPerformed(evt);
            }
        });

        btnBuscarMusica.setText("Buscar");

        lblTitulo.setText("Título");

        lblImagemMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/poze musica.png"))); // NOI18N

        lblArtista.setText("Artista");

        lblAcordeMusica.setText("Acorde");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagemMusica)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArtista)
                            .addComponent(lblTitulo)
                            .addComponent(lblAcordeMusica)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarMusica)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMusica))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblTitulo)
                        .addGap(30, 30, 30)
                        .addComponent(lblArtista)
                        .addGap(35, 35, 35)
                        .addComponent(lblAcordeMusica))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagemMusica)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaMusicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMusica;
    private javax.swing.JLabel lblAcordeMusica;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblImagemMusica;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBuscaMusica;
    // End of variables declaration//GEN-END:variables
}
